server:
  port: 10000
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  application:
    name: eurekaService
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10000/eureka
security:
  basic:
    enabled: true
  user:
    name: ylw
    password: ylw1997