server:
  port: 10004
  servlet:
    context-path: /Article
spring:
  application:
    name: articleService
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ftui.common.pojo
  configuration:
    map-underscore-to-camel-case: true


