spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ft_ui?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: 39.105.190.207:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: myGroup
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/