server:
  port: 10003
  servlet:
    context-path: /Admin
  servletPath: /Admin
spring:
  application:
    name: adminService
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ftui.common.pojo
  configuration:
    map-underscore-to-camel-case: true
eureka:
  instance:
    statusPageUrlPath: ${server.servletPath}/info


