server:
  port: 10003
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
  application:
    name: adminService
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
