server:
  port: 10001
spring:
  application:
    name: zuulService
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
zuul:
  routes:
    userService: /userService/**
