server:
  port: 10002
spring:
  application:
    name: userService
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ftui.common.pojo
  configuration:
    map-underscore-to-camel-case: true
    

