server:
  port: 8092


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ft.common.pojo
  configuration:
    map-underscore-to-camel-case: true

spring:
  profiles:
    active:  #spring.profiles.active#
  application:
    name: adminService

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  rowBoundsWithCount: true
  pageSizeZero: true



